### ISSUE TITLE
Depend on upstream ruamel.yaml instead of unmaintained ruamel_yaml

### ISSUE THREAD

**Issue by mbargull** [conda-forge/cantera-feedstock#32]
### Comment:

I'm currently looking at what packages on conda-forge have a dependency on the non-maintained `ruamel_yaml` package.

It'd be good if we could have this package depend on `ruamel.yaml` instead of `ruamel_yaml`, too.

NB: The latest `conda-forge::ruamel_yaml` is still at version `0.15.80` -- upstream released that version 5 years ago.

----
I `grep`ped Cantera's repository for uses of `ruamel_yaml`/`ruamel.yaml` and `ruamel_yaml` is only ever used as a fallback.
That's great! So, I'd assume we could just replace `ruamel_yaml` with `ruamel.yaml` in the recipe and be set.

While looking at the `ruamel.yaml` uses, I also looked out for uses of the deprecated top-level `*load`/`*dump` functions which have been removed in `ruamel.yaml=0.18`.
The single case I found which uses one of those (not as a fallback) is https://github.com/Cantera/cantera/blob/v3.0.0/interfaces/sourcegen/sourcegen/_orchestrate.py#L26 .

----

**Comment by bryanwweber** [comment]
We are using `ruamel_yaml` to be able to support the dependency from the defaults channel. If `ruamel.yaml` is available there, we can make this changeover upstream in Cantera. Otherwise, this should IMO be a patch for this recipe.

**Comment by mbargull** [comment]
Yes, `defaults` started to ship `ruamel.yaml` since version `0.16.5` some years back.
(In the first years of Conda/Anaconda distribution, `ruamel` being a namespace package created some issues (can't remember the details) which is why they put out `ruamel_yaml` as a workaround -- and stuck with it quite a bit longer than necessary.)
Now even `conda>=22.10` itself depends on `ruamel.yaml` instead of `ruamel_yaml` which is why you can assume good availability in `defaults` :).

**Comment by bryanwweber** [comment]
Awesome. Yes, I do recall it was something like conda not supporting namespace packages at the time. If you want to make an upstream PR to replace these uses, that would be supported I believe. The only caveat in general is that we support Ubuntu 20.04 natively (i.e., from apt) which has [ruamel.yaml =0.15.89](https://packages.ubuntu.com/focal/python3-ruamel.yaml), so we can't rely on features from newer versions. The sourcegen code is only run at build time, so that shouldn't need to be changed.
